### ISSUE TITLE
What changes should the codemod do?

### ISSUE THREAD

**Issue by Kludex** [pydantic/bump-pydantic#1]
## Checklist

- [x] Config class to `model_config` attribute on BaseModel.
- [x] ~Replace imports that changed location .e.g. `pydantic.json` to `pydantic.deprecated.json`.~ I'm not doing this, since it's changing one that is deprecated, for the other that is deprecated as well.
- [ ] Replace [method names](https://github.com/pydantic/pydantic/blob/c71b2db3aac13a59bedfc03efc35e6a5acae3597/pydantic/main.py#L643-L874). 
- [x] Add `None` default value to `Union[T, None]`, `Optional[None]` and `Any`.
- [x] `Field` keywords renaming.
- [x] Remove `Extra` import, and replace by string e.g. `Extra.allow` -> `"allow"`.
- [x] ~Warn on `Color` and `PaymentMethod` when not using `pydantic-extra-types`.~ Replace `Color` and `PaymentCardNumber` from `pydantic` to `pydantic-extra-types`.
- [x] Replace `from pydantic import BaseSettings` by `from pydantic_settings import BaseSettings`.
- [x] Replace `Field(env=<str>)` by `Field(validation_alias=<str>)`.
- [x] Replace `GenericModel, Generic[T]` by `BaseModel, Generic[T]`.
- [x] Replace `__root__` to `RootModel`.

The [migration guide](https://docs.pydantic.dev/dev-v2/migration/) may help here.

**Comment by samuelcolvin** [comment]
See [here](https://github.com/pydantic/pydantic/blob/c71b2db3aac13a59bedfc03efc35e6a5acae3597/pydantic/main.py#L643-L874) for the main methods to change.

**Comment by Kludex** [comment]
I'll close this, since I've achieved almost everything that I wanted.

The only thing that is missing is the replacement of method calls.
