### ISSUE TITLE
Mark methods on arbitrary classes 

### ISSUE THREAD

**Issue by JensHeinrich** [pydantic/bump-pydantic#106]
pydantic specific methods like `__get_validators__` should be marked with a TODO on arbitrary classes to make migration of custom types easier

**Comment by Kludex** [comment]
What comment would you like to see?

**Comment by Kludex** [comment]
Sure. Would you like to create a PR for it?

**Comment by JensHeinrich** [comment]
I can try, if I understand the current mode of operation

**Comment by Kludex** [comment]
Thanks.
