### ISSUE TITLE
Conversion of conint is losing the type int

### ISSUE THREAD

**Issue by lgosselin** [pydantic/bump-pydantic#109]
I think I have a small issue for BP008 part.

This model:
```
class MyModel(BaseModel):
    # ...
    some_id: Optional[conint(ge=1, le=4294967295)] = None
```
will be turned into:
```
class MyModel(BaseModel):
    # ...
    some_id: Optional[Field(ge=1, le=4294967295)] = None
```

At runtime, we will get this exception:
`TypeError: typing.Optional requires a single type. Got FieldInfo(annotation=NoneType, required=True, metadata=[Ge(ge=1), Le(le=4294967295)])`

I was expecting a model along the line of:
```
class MyModel(BaseModel):
    # ...
    some_id: Optional[Annotated[int, Field(ge=1, le=4294967295)]] = None
```

**Comment by Kludex** [comment]
Oh! My bad.

Yeah, I'll fix it tomorrow.

**Comment by lgosselin** [comment]
Thanks. I was working on a very small project so it was straight-forward for me to fix this manually. But it may help larger projects during their migration.
