### ISSUE TITLE
RecursionError when processing file with a large number of enums

### ISSUE THREAD

**Issue by ErnestoLoma** [pydantic/bump-pydantic#119]
I'm getting the following error:
RecursionError: maximum recursion depth exceeded while calling a Python object
When running bump-pydantic on a file containing a very large number of enum. 
Attached is a sample file that causes the problem. If you uncomment the last line the error will occur. 
I'm using bump-pydantic 0.6.1 with python 3.9.12
[enums.py.zip](https://github.com/pydantic/bump-pydantic/files/12370314/enums.py.zip)

**Comment by Kludex** [comment]
Please report it to [LibCST](https://github.com/Instagram/LibCST).

There's nothing we can do on `bump-pydantic` about it.
