### ISSUE TITLE
License info missing in classifiers and/or meta data

### ISSUE THREAD

**Issue by daveshih01** [pydantic/bump-pydantic#130]
Sorry to bother you.
Larger enterprises scan packages before allowing them into their internal pypi index, and one of the things they scan for is the license information.  This is typically done via scanning the meta data (whatever `pip show` reports) and  `classifiers` in `pyproject.toml`.  Please can you add the necessary license information in both places?  Thanks much!
You can mirror what the main `pydantic` package is doing because that one is working and passed our internal scanner.

**Comment by Kludex** [comment]
Would you mind sending a PR with it? I'll shortly make a release with it. I thought everything was fine license wise, but I can see it's not mentioned on PyPI.

**Comment by daveshih01** [comment]
Sorry about the delay.  I've created the PR at https://github.com/pydantic/bump-pydantic/pull/131
First PR ever in github so please excuse me for missing stuff.  Thanks.

**Comment by Kludex** [comment]
- Closed by https://github.com/pydantic/bump-pydantic/pull/131
