### ISSUE TITLE
[BUG]: bumb-pydantic doesnt change files

### ISSUE THREAD

**Issue by jjfantini** [pydantic/bump-pydantic#135]
OS: Wndows 11
IDE: Cursor

I am in a fresh [fork ](https://github.com/jjfantini/patito.git) of `patito` in local dev, using a conda env.

THHs depends on pydantic v1 and I am looking to change to support v2, thus using `bump-pydantic`

```bash
(venv_patito)PS C:\Users\<user>\<wd>\patito> bump-pydantic src/patito
[10:38:16] Start bump-pydantic.                                                                                         main.py:61
           Found 10 files to process                                                                                    main.py:76
[10:38:32] Run successfully!                                                                                           main.py:149
(venv_patito)PS C:\Users\<user>\<wd>\patito> 
```                                   

However, git doesn't track any changes and only generates an empty `log.txt` file. I've also been in src directory with the same outcome.

Shouldn't I get an error somewhere?

**Comment by jjfantini** [comment]
https://github.com/pydantic/bump-pydantic/assets/63276164/5a88e99f-f719-483e-aeae-2f8556a91eb8


https://github.com/pydantic/bump-pydantic/assets/63276164/7c07244e-2367-4489-9fa0-b7de10f89aff

**Comment by Kludex** [comment]
I think the problem here is that you didn't receive a message saying "No files were modified."
