### ISSUE TITLE
Set libcst dependency version

### ISSUE THREAD

**Issue by mojimi** [pydantic/bump-pydantic#136]
Hi, I installed this project into a venv that already had `libcst==0.3` installed, but it didn't work because the `calculate_module_and_package` function was only introduced in in [libcst 0.4.2](https://github.com/Instagram/LibCST/commit/914b18339d0cce12d4de8db7593ea9d1819c363a)

**Comment by Kludex** [comment]
PR welcome to set the minimum version to 0.4.2.
