### ISSUE TITLE
Imports ConfigDict from pydantic instead from pydantic_settings

### ISSUE THREAD

**Issue by sr-verde** [pydantic/bump-pydantic#52]
As a follow-up from [this non-issue in pydantic_settings](https://github.com/pydantic/pydantic-settings/issues/103#issuecomment-1621443699), I want to file this issue here. pydantic-bump seem to import `ConfigDict` from wrong package. And – if I got it right – it should import `SettingsConfigDict` in my example instead of `ConfigDict`.

I had this config in Pydantic v1:

```python
from typing import Literal
from pydantic import BaseSettings


class Config(BaseSettings):
    log_level: Literal["NOTSET", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "WARNING"

    class Config:
        env_file = ".env"
```

Then, I executed dump-pydantic and got the following config file:

```python
from typing import Literal
from pydantic import ConfigDict
from pydantic_settings import BaseSettings


class Config(BaseSettings):
    log_level: Literal["NOTSET", "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"] = "WARNING"
    model_config = ConfigDict(env_file=".env")
```

As one can see bump-pydantic imported `ConfigDict` from pydantic instead from `pydantic_settings`. And as the [example](https://docs.pydantic.dev/latest/usage/pydantic_settings/#dotenv-env-support) uses `SettingsConfigDict`, I think bump-pydantic should use that as well.

**Comment by Kludex** [comment]
Yep. I'll fix this.
