### ISSUE TITLE
Feature request: ignore patterns for files or directories

### ISSUE THREAD

**Issue by lemonyte** [pydantic/bump-pydantic#57]
Currently, bump-pydantic considers all files ending in `.py` when scanning and applying modifications. In a codebase where source files are located at the project root, and a virtual environment is present, bump-pydantic takes a very long time to go through everything in the virtual environment's `site-packages` in addition to the actual project source files.

Allowing the user to specify patterns to ignore when scanning, using a command-line argument, will solve this problem.

Further, some default patterns may be put in place, for example:

- Ignoring `.venv` as it is a common name for virtual environment directories, or
- Ignoring everything in `.gitignore` if it is present, if not falling back to the previous point

If the user wishes to suppress default ignore patterns, they might do so using `--ignore=""` or something similar.
These implementation details are up to the maintainers to decide.

If this feature is approved, I would like to work on it.

**Comment by Kludex** [comment]
PR welcome. 👍
