### ISSUE TITLE
Wrong conversion of allow_mutation

### ISSUE THREAD

**Issue by orfisko** [pydantic/bump-pydantic#60]
-    colour: t.Optional[t.Union[Colour, Finish]] = Field(allow_mutation=False)
+    colour: t.Optional[t.Union[Colour, Finish]] = Field(frozen=False)

Frozen should get value True here

**Comment by Kludex** [comment]
Right. Want to open a PR with a fix? 👀 🙏

**Comment by orfisko** [comment]
Right, that's done. Was a bit overwhelmed with how the code functions, bit of a masterclass in functional programming for me :).
