### ISSUE TITLE
"Usage" reference in README seems incomplete

### ISSUE THREAD

**Issue by keul** [pydantic/bump-pydantic#64]
… or at least can be confusing.

If I read https://docs.pydantic.dev/latest/migration/#code-transformation-tool it seem I have to `cd` inside the package directory:

> The usage is simple. If your project structure is:
>
>
> ```
> * repo_folder
>     * my_package
>         * <python source files> ...
> ```
> Then you'll want to do:
> ```
> cd /path/to/repo_folder
> bump-pydantic my_package
> ```

…while currently the readme does not mention this, it just sais "bump-pydantic <package>".

**Comment by Kludex** [comment]
Yeah... I thought doing that was needed, but it looks like you can invoke `bump-pydantic` from anywhere.

PR welcome on Pydantic to remove the `cd` part.

**Comment by keul** [comment]
OK, so the fact that this tool is not working for me both with `cd` and without is probably argument for another issue

**Comment by Kludex** [comment]
Whats the issue?

**Comment by keul** [comment]
> Whats the issue?

Still investigating, I will open a new issue report in case

**Comment by Kludex** [comment]
Thanks. :)
