### ISSUE TITLE
Update usage docs to align with navigation details

### ISSUE THREAD

**Issue by sberke-intc** [pydantic/bump-pydantic#78]
Ended up using the usage docs from https://docs.pydantic.dev/dev-v2/migration/ instead of the README.md

https://github.com/pydantic/bump-pydantic/blob/f43957af84901bcdd5f5112d54201869323226b7/README.md?plain=1#L52

The details about navigating to the parent folder is helpful as I found the reference of `package` to be ambiguous.

So this part was helpful:

![image](https://github.com/pydantic/bump-pydantic/assets/101284334/c1cc5c58-bd7b-4911-bc4d-344d529e9ae5)

**Comment by Kludex** [comment]
PR welcome. 👀
